### ISSUE TITLE
Create Glue Script

### ISSUE THREAD

**Issue by bpmweel** [nlesc-sherlock/deeplearning#96]
Create a glue script that runs the docker images.

Current design idea:

The script will be called with a directory with images as an input, and output directory and a temporary directory:
```sh
image_classify_workflow.py ~/input/ ~/out /tmp
```

 - [x] The script will then walk this directory and find every image in it and add it to an input.json
 - [x] The script will then call an object detection docker with this input directory.
 - [x] Give the output of this to a cropping tool.
 - [x] Give the output of the cropper to a number of more specific classifiers
 - [x] Give the output to the cropper again after face detection
 - [x] Give this output to age and gender classifiers
 - [x] Copy output json and cropped files to output directory

The final output is put in the output file.

**Comment by bpmweel** [comment]
The workflow is done and everything is now in github and should be on dockerhub. Can other people test this?

I will test more myself using the coco dataset.

**Comment by egpbos** [comment]
Could you give an example of how to test? That could also serve as (minimal) documentation.

**Comment by bpmweel** [comment]
To test you need to do the following:

1) Make sure docker, nvidia-docker, cuda-7.5 and cudnn5 are installed on the system.
2) Create a directory with your images in them. The images can be in sub-directories of this image.
3) Create a directory where the output should be stored. The script will put the output json and all the cropped images in this directory.
4) Call the script, which is located in the scripts folder, as follows:

```sh
$ ./image_classify_workflow.py <input_dir> <output_dir> <tmp_dir>
```
* The tmp dir is the directory where intermediary results are stored. I suggest using the system temp directory.

**Comment by egpbos** [comment]
Testing on dl-primus. I'm using conda for Python. This was my existing Python environment:

```sh
$ pip freeze
appdirs==1.4.0
click==6.6
conda==4.2.13
decorator==4.0.10
enum34==1.1.6
Flask==0.11.1
h5py==2.6.0
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
numpy==1.11.2
PIL==1.1.7
py==1.4.31
pycosat==0.6.1
pycrypto==2.6.1
pytest==3.0.5
pytools==2016.2.6
requests==2.11.1
ruamel-yaml===-VERSION
scipy==0.18.1
six==1.10.0
Werkzeug==0.11.11
WTForms==2.1
```

I have some faces in `/data/patrick_data/faces`, made an output dir at `/data/patrick_data/workflow_out` and used `/tmp` for tmp.

```sh
patrick@sherlock-demo:~/deeplearning$ scripts/image_classify_workflow.py /data/patrick_data/faces /data/patrick_data/workflow_out /tmp
```

The first attempt told me I had no Python docker package. **Perhaps add this to requirements?**

I pip installed docker and then it started running.

```sh
***************************************************
*                                                 *
*  Welcome to the image classification workflow.  *
*        This version is a python script.         *
*                                                 *
***************************************************


Now parsing arguments.....done.



Now setting up the docker environment.........done.


Now searching for files in input directory...Traceback (most recent call last):
  File "scripts/image_classify_workflow.py", line 162, in <module>
    with file(input_json, 'w') as outfile:
IOError: [Errno 13] Permission denied: '/tmp/files.json'
```

**Comment by egpbos** [comment]
The problem was that bweel already had an existing files.json there :P **Use a different tmp dir (or create one under /tmp for each run)**.

```sh
patrick@sherlock-demo:~/deeplearning$ mkdir /tmp/bieten
patrick@sherlock-demo:~/deeplearning$ scripts/image_classify_workflow.py /data/patrick_data/faces /data/patrick_data/workflow_out /tmp/bieten
***************************************************
*                                                 *
*  Welcome to the image classification workflow.  *
*        This version is a python script.         *
*                                                 *
***************************************************


Now parsing arguments.....done.



Now setting up the docker environment.........done.


Now searching for files in input directory...done.
Input filepaths written to:  /tmp/bieten/files.json 


Now running object detection...libdc1394 error: Failed to initialize libdc1394
done.
Now running cropping...done.
Now running car color classification...Command:  nvidia-docker run -v /data/patrick_data/faces:/data -v /tmp/bieten/cropped:/cropped -v /tmp/bieten:/temp -v /data/patrick_data/workflow_out:/out nlescsherlockdl/car_color_workflow --workflow_out /temp/colored.json /temp/cropped.json
libdc1394 error: Failed to initialize libdc1394
Namespace(batch_size=0, channel_swap=[2, 1, 0], data_path='/data', gpu_id=-1, gray_range=255, json=True, json_input_file=<open file '/temp/cropped.json', mode 'r' at 0x7f141c9f1db0>, mean_pixel_name='mean.binaryproto', model_deploy='deploy.prototxt', model_labels='labels.txt', model_path='/opt/deeplearning/Models/car_color', model_snapshot='snapshot_iter_63400.caffemodel', outfile=<open file '<stdout>', mode 'w' at 0x7f1463686150>, verbose=0, workflow_out=<open file '/temp/colored.json', mode 'w' at 0x7f141c9f1d20>)
Traceback (most recent call last):
  File "/opt/deeplearning/scripts/image_classify_workflow_wrap_car_color.py", line 57, in <module>
    raise Exception("No cars in input json file.")
Exception: No cars in input json file.
done.
Now running car model classification...Traceback (most recent call last):
  File "scripts/image_classify_workflow.py", line 213, in <module>
    raise Exception("Input file " + input_file + " was empty")
Exception: Input file /tmp/bieten/colored.json was empty
```

**Comment by egpbos** [comment]
I tried removing the input file Exceptions, but now realize that probably wasn't the way to go... Perhaps I should leave it at this for today :)
